<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <PublishUrl>publish\</PublishUrl>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishReadyToRun>true</PublishReadyToRun>
    <SelfContained>true</SelfContained>
    <AssemblyVersion>10.0.0</AssemblyVersion>
    <FileVersion>10.0.0</FileVersion>
    <Version>10.0.0</Version>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <PropertyGroup>
    <NeutralLanguage>en-US</NeutralLanguage>
    <NeutralResourcesLanguage>en-US</NeutralResourcesLanguage>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>BorderlessGaming_new.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Facepunch.Steamworks">
      <HintPath>..\SteamLibs\Facepunch.Steamworks.Win64.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="BorderlessGaming_new.ico" />
    <EmbeddedResource Include="Resources\master-glyph.png" />
    <EmbeddedResource Include="Windows\AppWPF.xaml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="Properties\Resources.de.resx" />
    <EmbeddedResource Remove="Properties\Resources.ru.resx" />
    <EmbeddedResource Remove="Properties\Resources.zh-CN.resx" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="app.manifest" />
  </ItemGroup>
  <ItemGroup>
    <Page Remove="Windows\AppWPF.xaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="bebop" Version="2.7.4" />
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="4.7.25104.5739" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="TaskScheduler" Version="2.10.1" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.183" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="../SteamLibs/steam_api64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Pack>true</Pack>
      <PackagePath>runtimes/win-x64/native/steam_api64.dll</PackagePath>
    </Content>
    <Content Include="../SteamLibs/steam_appid.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Pack>true</Pack>
      <PackagePath>runtimes/win-x64/native/steam_appid.txt</PackagePath>
    </Content>
  </ItemGroup>
  <Target Name="ZipLanguages" BeforeTargets="Build">
    <ZipDirectory SourceDirectory="$(ProjectDir)..\Languages" DestinationFile="$(OutputPath)\Languages.zip" Overwrite="true" />
  </Target>
  <Target Name="ZipLanguages" BeforeTargets="Publish">
    <ZipDirectory SourceDirectory="$(ProjectDir)..\Languages" DestinationFile="$(PublishDir)\Languages.zip" Overwrite="true" />
  </Target>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup Label="XAML Designer">
    <Page Update="$(ProjectDir)Windows\AboutWPF.xaml" Generator="MSBuild:Compile" XamlRuntime="Wpf" SubType="Designer" LogicalName="BorderlessGaming.NekoBoiNick.Resources.XAML.About.xaml" />
    <EmbeddedResource Update="$(ProjectDir)Dialog\AppWPF.xaml" Generator="MSBuild:Compile" XamlRuntime="Wpf" SubType="Designer" LogicalName="BorderlessGaming.NekoBoiNick.Resources.XAML.App.xaml" />
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <Page Update="$(ProjectDir)Windows\DesktopAreaSelectorWPF.xaml" Generator="MSBuild:Compile" XamlRuntime="Wpf" SubType="Designer" LogicalName="BorderlessGaming.NekoBoiNick.Resources.XAML.DesktopAreaSelector.xaml" />
    <Page Update="$(ProjectDir)Dialog\InputSizeWPF.xaml" Generator="MSBuild:Compile" XamlRuntime="Wpf" SubType="Designer" LogicalName="BorderlessGaming.NekoBoiNick.Resources.XAML.InputSize.xaml" />
    <Page Update="$(ProjectDir)Dialog\InputTextWPF.xaml" Generator="MSBuild:Compile" XamlRuntime="Wpf" SubType="Designer" LogicalName="BorderlessGaming.NekoBoiNick.Resources.XAML.InputText.xaml" />
    <Page Update="$(ProjectDir)Dialog\MainWindowWPF.xaml" Generator="MSBuild:Compile" XamlRuntime="Wpf" SubType="Designer" LogicalName="BorderlessGaming.NekoBoiNick.Resources.XAML.MainWindow.xaml" />
  </ItemGroup>
</Project>